export const surprimseMePrompts = [
  "A surreal underwater cityscape with floating jellyfish buildings.",
  "A flamingo playing a saxophone on a tropical beach at sunset.",
  "A steampunk-inspired tea party with mechanical animals and futuristic teapots.",
  "A majestic unicorn made entirely of flowers in a vibrant meadow.",
  "A sushi roll that transforms into a dragon mid-bite.",
  "A serene forest scene with glowing mushrooms and fairies.",
  "A futuristic cityscape with flying cars and holographic billboards.",
  "An elegant ball gown made of swirling galaxies and constellations.",
  "A robot chef cooking a meal using ingredients from a futuristic garden.",
  "A carousel filled with mythical creatures like griffins and centaurs.",
  "A floating island suspended in the sky with waterfalls cascading into the void.",
  "A mosaic portrait of a famous historical figure made entirely of puzzle pieces.",
  "A whimsical library where books come to life and interact with readers.",
  "A cake that looks like a realistic replica of planet Earth.",
  "A treehouse made of candy and chocolate, nestled in a candyland forest.",
  "A pair of shoes made of rainbow-colored glass that reflects the surrounding environment.",
  "A spaceship shaped like a giant seashell exploring an alien ocean planet.",
  "A futuristic robot band performing on a stage made of holographic light.",
  "A hot air balloon ride through a sky filled with floating lanterns.",
  "A fantastical garden with plants that bloom into musical instruments.",
  "A surreal chessboard where the pieces are miniature cities and landmarks.",
  "A whimsical steampunk-inspired flying machine powered by colorful balloons.",
  "A fantastical ice cream parlor with flavors that change based on the customer's mood.",
  "A cityscape made entirely of candy, with gingerbread houses and lollipop lampposts.",
  "A mysterious door that opens to reveal a hidden world filled with floating islands.",
  "A robot pet that can transform into any animal based on the owner's preference.",
  "A futuristic fashion runway with models wearing clothing made of light and energy.",
  "A magical forest with trees that change colors based on the seasons.",
  "A surreal desert landscape with sand dunes that resemble rolling ocean waves.",
  "A futuristic amusement park with gravity-defying roller coasters and virtual reality rides.",
  "A spaceship designed like a giant seashell exploring the depths of an alien ocean.",
  "A magical bookstore where books fly off the shelves and guide readers through their stories.",
  "A city skyline made entirely of colorful origami structures.",
  "A fantasy kingdom with floating islands and waterfalls that flow upwards.",
  "A futuristic transportation system with levitating pods and magnetic highways.",
  "A robot companion that can shapeshift into different animals or objects.",
  "A mesmerizing light show created by a swarm of fireflies in a moonlit forest.",
  "A surreal art gallery where paintings come to life and interact with viewers.",
  "A whimsical tea party with talking animals and floating teacups.",
  "A futuristic aquarium with robotic fish and underwater plants that glow in the dark.",
  "A fantasy castle with turrets made of candy and a moat filled with rainbow-colored liquid.",
  "A music festival where the instruments are made of unconventional materials like glass and ice.",
  "A floating cityscape above the clouds with skyscrapers made of crystal.",
  "A mystical forest with trees that have doors leading to different dimensions.",
  "A robot gardener that creates intricate patterns with flowers in a vast garden.",
  "A surreal circus with acrobats performing on floating platforms and trapeze artists swinging through the air.",
  "A futuristic laboratory with glowing test tubes and robotic scientists conducting experiments.",
  "A magical potion shop with shelves filled with colorful vials and bubbling cauldrons.",
  "A hidden cave filled with sparkling gemstones and glowing mushrooms.",
  "A futuristic beach resort with holographic palm trees and robotic waiters serving drinks.",
];